# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectTune' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectTune
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git', :branch => 'wip/swift4'
  pod 'Alamofire', '~> 4.5'
  pod 'PromiseKit', '~> 6.0'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'  
target 'ProjectTuneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
